apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
spec:
  type: NodePort
  selector:
    app: lanchonete-deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100