apiVersion: v1
kind: Service
metadata:
  name: lanchonete-lb-svc
spec:
  selector:
    app: lanchonete-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
