name: deploy

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: actions/checkout@v2
      - name: Apply database config
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply -f kubernetes/postgres/"
        env:
          EKS_CLUSTER: demo  

      - uses: actions/checkout@v2
      - name: Apply application deploy
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply -f kubernetes/"
        env:
          EKS_CLUSTER: demo  

      - uses: actions/checkout@v2
      - name: Verify 
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "get svc"
        env:
          EKS_CLUSTER: demo  


          
        
