name: deploy

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      CLUSTER_NAME: demo
    steps:
      - uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run database config
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply -f kubernetes/postgres/"
        env:
          EKS_CLUSTER: ${{ env.CLUSTER_NAME }}

      - name: Run application deploy
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "apply -f kubernetes/"
        env:
          EKS_CLUSTER: ${{ env.CLUSTER_NAME }} 

      - name: Run get loadbalancer service
        uses: nikosch86/github-action-eks-kubectl@main
        with:
          command: "get svc lanchonete-lb-svc"
        env:
          EKS_CLUSTER: ${{ env.CLUSTER_NAME }}

     
    
